nextcloudappstore/urls.py
from allauth.account.views import signup
from allauth.socialaccount.views import signup as social_signup
from csp.decorators import csp_update
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import etag

from nextcloudappstore.core.caching import app_rating_etag
from nextcloudappstore.core.feeds import AppReleaseAtomFeed, AppReleaseRssFeed
from nextcloudappstore.core.views import CategoryAppListView, AppDetailView, \
    app_description, AppReleasesView, AppUploadView, AppRatingApi, \
    AppRegisterView
from nextcloudappstore.scaffolding.views import AppScaffoldingView

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^$', CategoryAppListView.as_view(), {'id': None}, name='home'),
    url(r"^signup/$", csp_update(**settings.CSP_SIGNUP)(signup),
        name="account_signup"),
    url(r"^social/signup/$", csp_update(**settings.CSP_SIGNUP)(social_signup),
        name="socialaccount_signup"),
    url(r'^', include('allauth.urls')),
    url(r'^categories/(?P<id>[\w]*)/?$', CategoryAppListView.as_view(),
        name='category-app-list'),
    url(r'^developer/apps/generate/?$', AppScaffoldingView.as_view(),
        name='app-scaffold'),
    url(r'^developer/apps/releases/new/?$', AppUploadView.as_view(),
        name='app-upload'),
    url(r'^developer/apps/new/?$', AppRegisterView.as_view(),
        name='app-register'),
    url(r'^apps/(?P<id>[\w_]+)/?$', AppDetailView.as_view(),
        name='app-detail'),
    url(r'^apps/(?P<id>[\w_]+)/releases/?$', AppReleasesView.as_view(),
        name='app-releases'),
    url(r'^apps/(?P<id>[\w_]+)/description/?$', app_description,
        name='app-description'),
    url(r'^apps/(?P<id>[\w_]+)/ratings.json$',
        etag(app_rating_etag)(AppRatingApi.as_view()), name='app-ratings'),
    url(r'^api/', include('nextcloudappstore.api.urls',
                          namespace='api')),
    url(r'^account/',
        include('nextcloudappstore.user.urls', namespace='user')),
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'feeds/releases.rss', AppReleaseRssFeed(), name='feeds-releases-rss'),
    url(r'feeds/releases.atom', AppReleaseAtomFeed(),
        name='feeds-releases-atom'),
)

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)), ]
    except ImportError:
        pass

nextcloudappstore/user/urls.py
from django.conf.urls import url

from nextcloudappstore.user.views import PasswordView, AccountView, \
    APITokenView, DeleteAccountView, ChangeLanguageView, TransferAppsView

app_name = 'user'

urlpatterns = [
    url(r'^$', AccountView.as_view(), name='account'),
    url(r'^transfer-apps/?$', TransferAppsView.as_view(),
        name='account-transfer-apps'),
    url(r'^transfer-apps/(?P<pk>[a-z0-9_]+)/?$', TransferAppsView.as_view(),
        name='account-transfer-app'),
    url(r'^password/?$', PasswordView.as_view(), name='account-password'),
    url(r'^token/?$', APITokenView.as_view(), name='account-api-token'),
    url(r'^delete/?$', DeleteAccountView.as_view(), name='account-deletion'),
    url(r'^change-language/?$', ChangeLanguageView.as_view(),
        name='account-change-language'),
]

nextcloudappstore/user/models.py
from django.db import models

# Create your models here.

nextcloudappstore/user/forms.py
from allauth.account.utils import filter_users_by_email
from django import forms
from django.contrib.auth import get_user_model
from django.forms import EmailField, CharField, PasswordInput
from django.utils.translation import ugettext_lazy as _
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget


class SignupFormRecaptcha(forms.Form):
    """integrate a recaptcha field."""
    recaptcha = ReCaptchaField(widget=ReCaptchaWidget())
    first_name = CharField(max_length=30, label=_('First name'))
    last_name = CharField(max_length=30, label=_('Last name'))

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()


class DeleteAccountForm(forms.Form):
    email = EmailField(required=True, label=_('Your e-mail address'))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if self.user and self.user.email == email:
            return email
        else:
            raise forms.ValidationError(_(
                'The given e-mail address does not match your e-mail address'))


class AccountForm(forms.ModelForm):
    passwd = CharField(widget=PasswordInput(), label=_('Confirm password'),
                       help_text=_('Password is required to prevent '
                                   'unauthorized users from changing your '
                                   'email address and resetting your '
                                   'password. This field does not update your '
                                   'password!'))

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

    def clean_email(self):
        value = self.cleaned_data['email']
        users = filter_users_by_email(value)
        if [u for u in users if u.pk != self.instance.pk]:
            msg = _(
                'This e-mail address is already associated with another '
                'account.')
            raise forms.ValidationError(msg)
        return value

    def clean_passwd(self):
        value = self.cleaned_data['passwd']
        if self.instance.check_password(value):
            return value
        else:
            raise forms.ValidationError(_('Invalid password'))

nextcloudappstore/user/views.py
from allauth.account.models import EmailAddress
from allauth.account.views import PasswordChangeView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from nextcloudappstore.core.models import App
from nextcloudappstore.user.forms import DeleteAccountForm, AccountForm


class TransferAppsView(LoginRequiredMixin, TemplateView):
    template_name = 'user/transfer-apps.html'

    def post(self, request, pk):
        app = get_object_or_404(App, pk=pk, owner=self.request.user)
        app.ownership_transfer_enabled = not app.ownership_transfer_enabled
        app.save()
        return redirect(reverse('user:account-transfer-apps'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apps'] = App.objects.filter(owner=self.request.user)
        context['acc_page'] = 'account-transfer-apps'
        return context


class ChangeLanguageView(LoginRequiredMixin, TemplateView):
    template_name = 'user/set-language.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['acc_page'] = 'account-change-language'
        return context


class DeleteAccountView(LoginRequiredMixin, TemplateView):
    template_name = 'user/delete-account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = DeleteAccountForm()
        context['acc_page'] = 'delete-account'
        return context

    def post(self, request, *args, **kwargs):
        form = DeleteAccountForm(request.POST, user=request.user)
        if form.is_valid():
            request.user.delete()
            return redirect(reverse_lazy('home'))
        else:
            return render(request, self.template_name, {'form': form})


class AccountView(LoginRequiredMixin, UpdateView):
    """Display and allow changing of the user's name."""

    template_name = 'user/account.html'
    template_name_suffix = ''
    form_class = AccountForm
    success_url = reverse_lazy('user:account')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['acc_page'] = 'account'
        return context

    def form_valid(self, form):
        email = EmailAddress.objects.get_primary(user=self.request.user)
        email.email = form.cleaned_data['email']
        email.save()
        messages.success(self.request, 'Account details saved.')
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user


class PasswordView(LoginRequiredMixin, PasswordChangeView):
    """Allow the user to change their password."""

    template_name = 'user/password.html'
    success_url = reverse_lazy('user:account-password')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['acc_page'] = 'password'
        return context


class APITokenView(LoginRequiredMixin, TemplateView):
    """Display the user's API token, and allow it to be regenerated."""

    template_name = 'user/api-token.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['acc_page'] = 'api-token'
        return context

nextcloudappstore/user/templates/user/account.html
{% extends "user/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block head-title %}{% trans 'Account' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Account" %}</h1>
    <section>
        <form action="{% url 'user:account' %}" method="post">
            {% include 'form-fields.html' %}
            <p><button class="btn btn-primary btn-block" type="submit">{% trans 'Save' %}</button></p>
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/api-token.html
{% extends "user/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block head %}
    <script defer src="{% static 'public/user/token.js' %}"></script>
{% endblock %}

{% block head-title %}{% trans 'API Token' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "API Token" %}</h1>
    <section id="tokenSection">
        <p>
            {% blocktrans %}
                The API token can be used for authentication when calling the app store
                <a href="https://nextcloudappstore.readthedocs.io/en/latest/restapi.html">REST API</a>.
                Make sure to keep it secret. A new token can be generated below, rendering the old token invalid.
            {% endblocktrans %}
        </p>

        <p>{% trans 'Your API token is:' %}</p>

        <!-- DO NOT print the HTML token here because of BREACH attack but fetch it with JS -->
        <p><code id="token"></code></p>
        <form action="{% url 'api:v1:user-token-new' %}" method="post" id="api-token-regen-form">
            <span data-l10n-id="msg-form-success" hidden>{% trans 'New API token generated.' %}</span>
            <div><div class="hidden alert alert-success global-success-msg" hidden></div></div>
            <div><div class="alert alert-danger global-error-msg" hidden></div></div>

            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-block" value="{% trans 'Regenerate API token' %}" disabled="disabled">
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/base.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block head-title %}{% trans "Account" %} - {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-3">
        <ul id="sidebar" class="nav nav-pills nav-stacked">
            <li class="{% if acc_page == 'account' %}active{% endif %}">
                <a href="{% url 'user:account' %}">{% trans 'Account' %}</a>
            </li>
            <li class="{% if acc_page == 'account-transfer-apps' %}active{% endif %}">
                <a href="{% url 'user:account-transfer-apps' %}">{% trans 'Transfer app ownership' %}</a>
            </li>
            <li class="{% if acc_page == 'account-change-language' %}active{% endif %}">
                <a href="{% url 'user:account-change-language' %}">{% trans 'Change language' %}</a>
            </li>
            {% if request.user.has_usable_password %}
                <li class="{% if acc_page == 'password' %}active{% endif %}">
                    <a href="{% url 'user:account-password' %}">{% trans 'Password' %}</a>
                </li>
            {% endif %}
            <li class="{% if acc_page == 'api-token' %}active{% endif %}">
                <a href="{% url 'user:account-api-token' %}">{% trans 'API token' %}</a>
            </li>
            <li class="{% if acc_page == 'delete-account' %}active{% endif %}">
                <a href="{% url 'user:account-deletion' %}">{% trans 'Delete account' %}</a>
            </li>
        </ul>
    </div>
    <div class="col-sm-9">
        {% block account-content %}{% endblock %}
    </div>
</div>
{% endblock %}

nextcloudappstore/user/templates/user/delete-account.html
{% extends "user/base.html" %}
{% load i18n %}
{% load account socialaccount css_class %}

{% block head-title %}{% trans "Delete account" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Delete account" %}</h1>
    <section>
        <p class="alert alert-danger">{% trans 'Deleting your account will delete all your apps and releases as well. To delete your account, insert your e-mail address into the input field and click the "Delete account" button:' %}</p>
        <form method="POST" action="{% url 'user:account-deletion' %}">
            {% include 'form-fields.html' %}
            <p><input type="submit" class="btn btn-danger btn-block" value="{% trans 'Delete account' %}"></p>
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/password.html
{% extends "user/base.html" %}
{% load i18n %}
{% load account socialaccount %}

{% block head-title %}{% trans "Password" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Change Password" %}</h1>
    <section>
        <p class="text-danger">{% trans 'Changing your password will also regenerate your API token!' %}</p>
        {% if request.user.has_usable_password %}
            <form method="POST" action="{% url 'user:account-password' %}" class="password_change">
                {% include 'form-fields.html' %}
                <p><button class="btn btn-primary btn-block" type="submit">{% trans "Change Password" %}</button></p>
            </form>
        {% else %}
            <p>{% trans 'You seem to be using an account registered with a third-party provider. Your password can therefore <strong>not</strong> be changed from this page.' %}</p>
        {% endif %}
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/set-language.html
{% extends "user/base.html" %}
{% load i18n %}

{% block head-title %}{% trans "Change language" %} - {% endblock %}

{% block account-content %}
    <h1>{% trans 'Change language' %}</h1>
    <section>
        <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <div class="form-group">
                <label title="{% trans 'required field' %}" class="control-label" for="language">{% trans 'Language' %}<span class="required-field">*</span></label>

                <select name="language" id="language" class="form-control">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </div>
            <p><input type="submit" class="btn btn-primary btn-block" value="{% trans 'Change language' %}"></p>
        </form>
    </section>
{% endblock %}

nextcloudappstore/user/templates/user/transfer-apps.html
{% extends "user/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block head-title %}{% trans 'Transfer Apps' %} - {% endblock %}

{% block account-content %}
    <h1>{% trans "Transfer Apps" %}</h1>
    <section>
        <p>{% trans 'To transfer an app to a new owner you must first unlock the app. A user can then take control of the app by registering it again on the app register page in the app developer menu.' %}</p>

        {% if apps %}
            <table class="table table-striped">
                <tr>
                    <th>{% trans 'App name' %}</th>
                    <th>{% trans 'Ownership transfer status' %}</th>
                    <th>{% trans 'Change ownership transfer status' %}</th>
                </tr>
                {% for app in apps %}
                    <tr>
                        <td>{{ app.name }}</td>
                        <td class="{% if app.ownership_transfer_enabled %}bg-success{% else %}bg-danger{% endif %}">
                            {% if app.ownership_transfer_enabled %}
                                {% trans 'Unlocked for transfer' %}
                            {% else %}
                                {% trans 'Locked, no transfer possible' %}
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'user:account-transfer-app' pk=app.id %}" method="post">
                                {% csrf_token %}
                                {% if app.ownership_transfer_enabled %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Lock ownership transfer' %}</button>
                                {% else %}
                                    <button class="btn btn-primary btn-block" type="submit">{% trans 'Unlock ownership transfer' %}</button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p class="alert alert-info">{% trans 'You have not uploaded any apps yet!' %}</p>
        {% endif %}
    </section>
{% endblock %}