nextcloudappstore/urls.py
from allauth.account.views import signup
from allauth.socialaccount.views import signup as social_signup
from csp.decorators import csp_update
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import etag

from nextcloudappstore.core.caching import app_rating_etag
from nextcloudappstore.core.feeds import AppReleaseAtomFeed, AppReleaseRssFeed
from nextcloudappstore.core.views import CategoryAppListView, AppDetailView, \
    app_description, AppReleasesView, AppUploadView, AppRatingApi, \
    AppRegisterView
from nextcloudappstore.scaffolding.views import AppScaffoldingView

admin.site.login = login_required(admin.site.login)

urlpatterns = [
    url(r'^$', CategoryAppListView.as_view(), {'id': None}, name='home'),
    url(r"^signup/$", csp_update(**settings.CSP_SIGNUP)(signup),
        name="account_signup"),
    url(r"^social/signup/$", csp_update(**settings.CSP_SIGNUP)(social_signup),
        name="socialaccount_signup"),
    url(r'^', include('allauth.urls')),
    url(r'^categories/(?P<id>[\w]*)/?$', CategoryAppListView.as_view(),
        name='category-app-list'),
    url(r'^developer/apps/generate/?$', AppScaffoldingView.as_view(),
        name='app-scaffold'),
    url(r'^developer/apps/releases/new/?$', AppUploadView.as_view(),
        name='app-upload'),
    url(r'^developer/apps/new/?$', AppRegisterView.as_view(),
        name='app-register'),
    url(r'^apps/(?P<id>[\w_]+)/?$', AppDetailView.as_view(),
        name='app-detail'),
    url(r'^apps/(?P<id>[\w_]+)/releases/?$', AppReleasesView.as_view(),
        name='app-releases'),
    url(r'^apps/(?P<id>[\w_]+)/description/?$', app_description,
        name='app-description'),
    url(r'^apps/(?P<id>[\w_]+)/ratings.json$',
        etag(app_rating_etag)(AppRatingApi.as_view()), name='app-ratings'),
    url(r'^api/', include('nextcloudappstore.api.urls',
                          namespace='api')),
    url(r'^account/',
        include('nextcloudappstore.user.urls', namespace='user')),
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    url(r'feeds/releases.rss', AppReleaseRssFeed(), name='feeds-releases-rss'),
    url(r'feeds/releases.atom', AppReleaseAtomFeed(),
        name='feeds-releases-atom'),
)

if settings.DEBUG:
    try:
        import debug_toolbar

        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)), ]
    except ImportError:
        pass

nextcloudappstore/user/urls.py
from django.conf.urls import url

from nextcloudappstore.user.views import PasswordView, AccountView, \
    APITokenView, DeleteAccountView, ChangeLanguageView, TransferAppsView

app_name = 'user'

urlpatterns = [
    url(r'^$', AccountView.as_view(), name='account'),
    url(r'^transfer-apps/?$', TransferAppsView.as_view(),
        name='account-transfer-apps'),
    url(r'^transfer-apps/(?P<pk>[a-z0-9_]+)/?$', TransferAppsView.as_view(),
        name='account-transfer-app'),
    url(r'^password/?$', PasswordView.as_view(), name='account-password'),
    url(r'^token/?$', APITokenView.as_view(), name='account-api-token'),
    url(r'^delete/?$', DeleteAccountView.as_view(), name='account-deletion'),
    url(r'^change-language/?$', ChangeLanguageView.as_view(),
        name='account-change-language'),
]

nextcloudappstore/core/forms.py
from django.conf import settings
from django.forms import Form, CharField, Textarea, ChoiceField, RadioSelect, \
    BooleanField, TextInput
from django.utils.translation import get_language_info, \
    ugettext_lazy as _  # type: ignore

from nextcloudappstore.core.models import App, AppRating

RATING_CHOICES = (
    (0.0, _('Bad')),
    (0.5, _('OK')),
    (1.0, _('Good'))
)

REGISTER_SIGN_CMD = ' echo -n "APP_ID" | openssl dgst -%s -sign ' \
                    '~/.nextcloud/certificates/APP_ID.key | openssl base64' % \
                    settings.CERTIFICATE_DIGEST
RELEASE_SIGN_CMD = (' openssl dgst -%s -sign '
                    '~/.nextcloud/certificates/APP_ID.key /path/to/app.tar.gz '
                    '| openssl base64' % settings.CERTIFICATE_DIGEST)
CREATE_CERT_CMD = ' openssl req -nodes -newkey rsa:4096 -keyout APP_ID.key ' \
                  '-out APP_ID.csr -subj "/CN=APP_ID"'


class AppReleaseUploadForm(Form):
    download = CharField(label=_('Download link (tar.gz)'), max_length=256,
                         widget=TextInput(attrs={'required': 'required'}))
    signature = CharField(widget=Textarea(attrs={'required': 'required'}),
                          label=_('Signature'),
                          help_text=_(
                              'Can be generated by executing the following '
                              'command:') + RELEASE_SIGN_CMD)
    nightly = BooleanField(label=_('Nightly'), required=False)


class AppRegisterForm(Form):
    certificate = CharField(
        widget=Textarea(attrs={'required': 'required'}),
        label=_('Public certificate'),
        help_text=_(
            'Usually stored in ~/.nextcloud/certificates/APP_ID.crt where '
            'APP_ID is your app\'s ID. If you do not have a certificate you '
            'need to create a certificate sign request (CSR) first, which '
            'should be posted on the <a '
            'href="https://github.com/nextcloud/app-certificate-requests" '
            'rel="noreferrer noopener">certificate repository</a> (follow '
            'the README). You can generate the CSR by executing the '
            'following command:') + CREATE_CERT_CMD)
    signature = CharField(widget=Textarea(attrs={'required': 'required'}),
                          label=_('Signature over your app\'s ID'),
                          help_text=_(
                              'Can be generated by executing the following '
                              'command:') + REGISTER_SIGN_CMD)
    safe_help_fields = ['certificate']


def get_languages_local(language=None):
    if language:
        languages = [language]
    else:
        languages = [l[0] for l in settings.LANGUAGES]

    return [(li['code'], li['name_local'])
            for li in [get_language_info(l) for l in languages]]


class AppRatingForm(Form):
    rating = ChoiceField(initial=0.5, choices=RATING_CHOICES,
                         widget=RadioSelect)
    language_code = ChoiceField(initial="", label=_('Language'),
                                choices=get_languages_local(),
                                help_text=_(
                                    '<b>Important</b>: Changing the language '
                                    'will clear your current comment. Changes '
                                    'will not be saved!')
                                )
    comment = CharField(widget=Textarea, required=False, label=_('Comment'))
    safe_help_fields = ['language_code']

    def __init__(self, *args, **kwargs):
        self._id = kwargs.pop('id', None)
        self._user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    class Meta:
        fields = ('rating', 'language_code', 'comment')

    def save(self):
        app = App.objects.get(id=self._id)
        app_rating, created = AppRating.objects.get_or_create(user=self._user,
                                                              app=app)
        app_rating.rating = self.cleaned_data['rating']
        app_rating.set_current_language(self.cleaned_data['language_code'])
        app_rating.comment = self.cleaned_data['comment']
        app_rating.save()

nextcloudappstore/core/views.py
from urllib.parse import urlencode

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.functional import cached_property
from django.utils.translation import get_language, get_language_info
from django.views.decorators.http import etag
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from rest_framework.generics import ListAPIView
from semantic_version import Version

from nextcloudappstore.core.caching import app_etag
from nextcloudappstore.core.facades import flatmap
from nextcloudappstore.core.forms import AppRatingForm, AppReleaseUploadForm, \
    AppRegisterForm
from nextcloudappstore.core.models import App, Category, AppRating
from nextcloudappstore.core.serializers import AppRatingSerializer
from nextcloudappstore.core.versioning import pad_min_version


@etag(app_etag)
def app_description(request, id):
    app = get_object_or_404(App, id=id)
    return HttpResponse(app.description, content_type='text/plain')


class AppRatingApi(ListAPIView):
    serializer_class = AppRatingSerializer

    def get_queryset(self):
        id = self.kwargs.get('id')
        lang = self.request.GET.get('lang', self.request.LANGUAGE_CODE)
        app = get_object_or_404(App, id=id)
        queryset = AppRating.objects.language(lang).filter(app=app)

        current_user = self.request.GET.get('current_user', 'false')
        if current_user == 'true':
            return queryset.filter(user=self.request.user)
        else:
            return queryset


class AppDetailView(DetailView):
    queryset = App.objects.prefetch_related(
        'releases',
        'screenshots',
        'co_maintainers',
        'translations',
    ).select_related('owner')
    template_name = 'app/detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'

    def post(self, request, id):
        form = AppRatingForm(request.POST, id=id, user=request.user)
        # there is no way that a rating can be invalid by default
        if form.is_valid() and request.user.is_authenticated:
            form.save()
        return redirect('app-detail', id=id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['DISCOURSE_URL'] = settings.DISCOURSE_URL.rstrip('/')
        context['rating_form'] = AppRatingForm(
            initial={'language_code': get_language()})

        ratings = AppRating.objects.filter(app=context['app'])
        rating_languages = flatmap(
            lambda r: r.get_available_languages(), ratings)

        # make sure current session language is in the list even if there are
        # no comments.
        rating_languages = list(rating_languages)
        if get_language() not in rating_languages:
            rating_languages.append(get_language())

        context['languages'] = set(sorted(rating_languages))
        context['fallbackLang'] = 'en' if 'en' in context['languages'] else ''
        context['user_has_rated_app'] = False
        if self.request.user.is_authenticated:
            try:
                app_rating = AppRating.objects.get(user=self.request.user,
                                                   app=context['app'])

                # if parler fallsback to a fallback language
                # it doesn't set the language as current language
                # and we can't select the correct language in the
                # frontend. So we try and find a languge that is
                # available
                language_code = app_rating.get_current_language()
                if not app_rating.has_translation(language_code):
                    for fallback in app_rating.get_fallback_languages():
                        if app_rating.has_translation(fallback):
                            app_rating.set_current_language(fallback)

                # when accessing an empty comment django-parler tries to
                # fall back to the default language. However for comments
                # the default (English) does not always exist. Unfortunately
                # it throws the same exception as non existing models,
                # so we need to access it beforehand
                try:
                    comment = app_rating.comment
                except AppRating.DoesNotExist:
                    comment = ''

                context['rating_form'] = AppRatingForm({
                    'rating': app_rating.rating,
                    'comment': comment,
                    'language_code': app_rating.get_current_language(),
                })
                context['user_has_rated_app'] = True
            except AppRating.DoesNotExist:
                pass
        context['categories'] = Category.objects.prefetch_related(
            'translations').all()
        context['latest_releases_by_platform_v'] = \
            self.object.latest_releases_by_platform_v()
        return context


class AppReleasesView(DetailView):
    queryset = App.objects.prefetch_related(
        'translations',
        'releases__translations',
        'releases__phpextensiondependencies__php_extension',
        'releases__databasedependencies__database',
        'releases__shell_commands',
        'releases__licenses',
    )
    template_name = 'app/releases.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.prefetch_related(
            'translations').all()

        releases = self.object.releases_by_platform_v()
        unstables = self.object.unstable_releases_by_platform_v()
        versions = set(list(releases.keys()) + list(unstables.keys()))
        all_releases = list(map(
            lambda v: (v, releases.get(v, []) + unstables.get(v, [])),
            versions))
        context['releases_by_platform_v'] = \
            self._sort_by_platform_v(all_releases)
        return context

    def _sort_by_platform_v(self, releases_by_platform, reverse=True):
        """Sorts a list of tuples like (<platform version>, [releases]) by
        platform version.

        :param releases_by_platform: A list of tuples.
        :param reverse: Descending order if True, ascending otherwise.
        :return sorted list of tuples.
        """

        return sorted(releases_by_platform, reverse=reverse,
                      key=lambda v: Version(pad_min_version(v[0])))


class CategoryAppListView(ListView):
    model = App
    template_name = 'app/list.html'
    allow_empty = True

    def get_queryset(self):
        order_by = self.request.GET.get('order_by', 'rating_overall')
        ordering = self.request.GET.get('ordering', 'desc')
        is_featured = self.request.GET.get('is_featured', False)
        maintainer = self.request.GET.get('maintainer', False)
        sort_columns = []

        allowed_order_by = {'name', 'last_release', 'rating_overall',
                            'rating_recent'}
        if order_by in allowed_order_by:
            if order_by == 'name':
                order_by = 'translations__name'
            if ordering == 'desc':
                sort_columns.append('-' + order_by)
            else:
                sort_columns.append(order_by)

        lang = get_language_info(get_language())['code']
        category_id = self.kwargs['id']
        queryset = App.objects.search(self.search_terms, lang).order_by(
            *sort_columns).filter(releases__gt=0)
        if maintainer:
            try:
                user = User.objects.get_by_natural_key(maintainer)
                queryset = queryset.filter(Q(owner=user) |
                                           Q(co_maintainers=user))
            except ObjectDoesNotExist:
                return queryset.none()
        if category_id:
            queryset = queryset.filter(categories__id=category_id)
        if is_featured == "true":
            queryset = queryset.filter(is_featured=True)
        return queryset.prefetch_related('screenshots', 'translations')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.prefetch_related(
            'translations').all()
        category_id = self.kwargs['id']
        if category_id:
            context['current_category'] = Category.objects.get(id=category_id)
        if self.search_terms:
            context['search_query'] = ' '.join(self.search_terms)
        context['url_params'] = self.url_params
        return context

    @cached_property
    def url_params(self):
        """URL encoded strings with the GET params of the last request.

        Intended for preserving GET params upon clicking a link by including
        one (and only one) of these strings in the "href" attribute.

        The parameters are divided into three groups: search, filters and
        ordering. In addition to these three, the returned dict also contains
        some combinations of them, as specified by the dict keys.

        No leading "?" or "&".

        :return dict with URL encoded strings.
        """

        search = self._url_params_str('search')
        filters = self._url_params_str('is_featured', 'maintainer')
        ordering = self._url_params_str('order_by', 'ordering')

        return {
            'search': search,
            'filters': filters,
            'ordering': ordering,
            'search_filters': self._join_url_params_strs(search, filters),
            'filters_ordering': self._join_url_params_strs(filters, ordering),
        }

    def _url_params_str(self, *params):

nextcloudappstore/core/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% trans 'The Nextcloud App Store - Upload your apps and install new apps onto your Nextcloud' %}">
    <meta name="author" content="{% trans 'The Nextcloud Community' %}">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.png' %}"/>
    <link rel="apple-touch-icon" href="{% static 'assets/img/favicon-180.png' %}">
    <title>{% block head-title %}{% endblock %}App Store - Nextcloud</title>
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}" charset="utf-8">
    <link rel="stylesheet"
          href="{% static 'vendor/bootstrap/dist/css/bootstrap.min.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'assets/css/theme.css' %}" charset="utf-8">
    {% block feeds %}
        <link rel="alternate" type="application/atom+xml" title="{% trans 'Latest app releases' %}" href="{% url 'feeds-releases-atom' %}" />
        <link rel="alternate" type="application/rss+xml" title="{% trans 'Latest app releases' %}" href="{% url 'feeds-releases-rss' %}" />
    {% endblock %}
    <script type="text/javascript" src="{% static 'vendor/bootstrap.native.min.js' %}" async></script>
    {% block head %}{% endblock %}
</head>

<body>
<div id="container">
    {% block navbar %}{% include 'nav.html' %}{% endblock %}
    <div class="container" id="body">
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                    {{ message }}
                </div>
            {% endfor %}
            {% block messages %}{% endblock %}
        </div>
        {% block content %}{% endblock %}
    </div>
    <footer class="navbar-default" id="footer">
        <div class="container">
            <ul class="nav navbar-nav navbar-left">
                <li class="nav-link">
                    <a href="https://github.com/nextcloud/appstore" rel="noreferrer noopener">{% trans 'Fork me on GitHub' %}</a>
                </li>
                <li class="nav-link">
                    <a href="https://nextcloud.com/privacy/" rel="noreferrer noopener">{% trans 'Privacy and legal' %}</a>
                </li>
                <li class="nav-link">
                    <a href="https://nextcloud.com/impressum/" rel="noreferrer noopener">{% trans 'Legal Notice' %}</a>
                </li>
            </ul>
        </div>
    </footer>
</div>
</body>
</html>

nextcloudappstore/core/templates/form-fields.html
{% load css_class field_type i18n %}
{% csrf_token %}
{% if form.non_field_errors  %}
    {% for error in form.non_field_errors %}
        <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
        <span class="sr-only">(error)</span>
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
{% endif %}
{% for field in form %}
    <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">

        {% if field|field_type == 'CheckboxInput' %}
            {{ field }}
            <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% else %}

            {% if field.field.required %}
                <label title="{% trans 'required field' %}" class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                    <span class="required-field">*</span>
                </label>
            {% else %}
                <label class="control-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
            {% endif %}

            {% if field|field_type == 'RadioSelect' %}
                {{ field }}
            {% else %}
                {{ field|css_class:'form-control' }}
            {% endif %}

        {% endif %}

        {% if field.errors %}
            {% for error in field.errors %}
                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                <span class="sr-only">(error)</span>
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        {% endif %}

        <!-- javascript errors -->
        <div hidden>
            <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
            <span class="sr-only">(error)</span>
            <p class="text-danger error-msg-{{field.name}}"></p>
        </div>

        {% if field.help_text %}
            {% if form.safe_help_fields and field.name in form.safe_help_fields %}
                <p class="help-block">{{ field.help_text|safe }}</p>
            {% else %}
                <p class="help-block">{{ field.help_text }}</p>
            {% endif %}
        {% endif %}
    </div>
{% endfor %}
{% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
{% endif %}

nextcloudappstore/core/templates/nav.html
{% load staticfiles %}
{% load i18n %}
<div class="banner">
    <div class="container">
        <a class="brand" href="/"><img class="logo" alt="Logo" src="{% static 'assets/img/small-logo.png' %}" title="nextcloud.com"><div class="site-title"></div></a>
        <form method="get"
              action="{% if current_category %}{{ request.path }}
                      {% else %}{% url 'home' %}
                      {% endif %}"
              class="search-form">
            <input type="search"
                   name="search"
                   role="search"
                   value="{{ search_query }}"
                   placeholder="{% if current_category %}{% blocktrans with category=current_category.name %}Search {{ category }}{% endblocktrans %}{% else %}{% trans 'Search all apps' %}{% endif %}"
                   class="form-control search-box">
            <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>

            {# Include all GET arguments that should be preserved when searching. #}
            {% if request.GET.order_by %}<input type="hidden" name="order_by" value="{{ request.GET.order_by }}">{% endif %}
            {% if request.GET.ordering %}<input type="hidden" name="ordering" value="{{ request.GET.ordering }}">{% endif %}

            <input type="submit" value="{% trans 'Search' %}" class="search-button">
        </form>
    </div>
</div>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">{% trans 'Toggle navigation' %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse ">
            <ul class="nav navbar-nav navbar-left">
                <li class="nav-link">
                    <a href="{% url 'home' %}">{% trans 'Apps' %}</a>
                </li>
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle nav-heading" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        {% trans 'App developer' %} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-link">
                            <a href="https://nextcloudappstore.readthedocs.io/en/latest/developer.html" rel="noopener noreferrer">{% trans 'Documentation' %}</a>
                        </li>
                        <li class="nav-link">
                            <a href="{% url 'app-scaffold' %}">{% trans 'Generate app' %}</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-link">
                                <a href="{% url 'app-register' %}">{% trans 'Register app' %}</a>
                            </li>
                            <li class="nav-link">
                                <a href="{% url 'app-upload' %}">{% trans 'Upload app release' %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_superuser %}
                    <li class="nav-link">
                        <a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-link">
                        <a href="{% url 'user:account' %}">{% trans 'Account' %}</a>
                    </li>
                    <li class="nav-link">
                        <a href="{% url 'account_logout' %}">{% trans 'Log out' %}</a>
                    </li>
                {% else %}
                    <li class="nav-link">
                        <a href="{% url 'account_login' %}">{% trans 'Log in' %}</a>
                    </li>
                    <li class="nav-link">
                        <a href="{% url 'account_signup' %}">{% trans 'Register' %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>